-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 20:54:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibSub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibSub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibSub` DEFAULT CHARACTER SET utf8 ;
USE `LibSub` ;

-- -----------------------------------------------------
-- Table `LibSub`.`Книги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Книги` (
  `Шифр книги` INT NOT NULL AUTO_INCREMENT,
  `название книги` VARCHAR(255) NULL,
  `первый автор` VARCHAR(45) NULL,
  `место издания` VARCHAR(45) NULL,
  `год издания` VARCHAR(45) NULL,
  `количество страниц` VARCHAR(45) NULL,
  `цена` VARCHAR(45) NULL,
  `Издательство` VARCHAR(45) NULL,
  PRIMARY KEY (`Шифр книги`));


-- -----------------------------------------------------
-- Table `LibSub`.`Экземпляры`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Экземпляры` (
  `инвентарный номер` INT NOT NULL AUTO_INCREMENT,
  `Книги_Шифр книги` INT NOT NULL,
  PRIMARY KEY (`инвентарный номер`),
  INDEX `fk_Экземпляры_Книги1_idx` (`Книги_Шифр книги` ASC) VISIBLE,
  CONSTRAINT `fk_Экземпляры_Книги1`
    FOREIGN KEY (`Книги_Шифр книги`)
    REFERENCES `LibSub`.`Книги` (`Шифр книги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `LibSub`.`Читатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Читатели` (
  `номер читательского билета` INT NOT NULL AUTO_INCREMENT,
  `Ф.И.О. читателя` VARCHAR(255) NULL,
  `дата рождения` DATE NULL,
  `телефон` VARCHAR(45) NULL,
  PRIMARY KEY (`номер читательского билета`));


-- -----------------------------------------------------
-- Table `LibSub`.`Тематические каталоги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Тематические каталоги` (
  `код темы` INT NOT NULL AUTO_INCREMENT,
  `наименование темы` VARCHAR(255) NULL,
  PRIMARY KEY (`код темы`));


-- -----------------------------------------------------
-- Table `LibSub`.`Книги_has_Тематические каталоги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Книги_has_Тематические каталоги` (
  `Книги_Шифр книги` INT NOT NULL,
  `Тематические каталоги_код темы` INT NOT NULL,
  PRIMARY KEY (`Книги_Шифр книги`, `Тематические каталоги_код темы`),
  INDEX `fk_Книги_has_Тематические каталоги_idx` (`Тематические каталоги_код темы` ASC) VISIBLE,
  INDEX `fk_Книги_has_Тематические каталоги_idx1` (`Книги_Шифр книги` ASC) VISIBLE,
  CONSTRAINT `fk_Книги_has_Тематические каталоги_`
    FOREIGN KEY (`Книги_Шифр книги`)
    REFERENCES `LibSub`.`Книги` (`Шифр книги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Книги_has_Тематические каталоги_1`
    FOREIGN KEY (`Тематические каталоги_код темы`)
    REFERENCES `LibSub`.`Тематические каталоги` (`код темы`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `LibSub`.`Читатели_has_Книги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibSub`.`Читатели_has_Книги` (
  `Читатели_номер читательского билета` INT NOT NULL,
  `Экземпляры_инвентарный номер` INT NOT NULL,
  `Дата выдачи` VARCHAR(45) DEFAULT NULL,
  `Дата возврата` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`Читатели_номер читательского билета`, `Экземпляры_инвентарный номер`),
  INDEX `fk_Читатели_has_Книги_Читатели1_idx` (`Читатели_номер читательского билета` ASC) VISIBLE,
  INDEX `fk_Читатели_has_Книги_Экземпляры1_idx` (`Экземпляры_инвентарный номер` ASC) VISIBLE,
  CONSTRAINT `fk_Читатели_has_Книги_Читатели1`
    FOREIGN KEY (`Читатели_номер читательского билета`)
    REFERENCES `LibSub`.`Читатели` (`номер читательского билета`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Читатели_has_Книги_Экземпляры1`
    FOREIGN KEY (`Экземпляры_инвентарный номер`)
    REFERENCES `LibSub`.`Экземпляры` (`инвентарный номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
